name: Docker deployment
 
on: [push]
 
jobs:
 build:
 
   runs-on: ubuntu-22.04
 
   steps:
   - uses: actions/checkout@v3
   - name: Set up Python 3.8
     uses: actions/setup-python@v3
     with:
       python-version: 3.8
   - name: psycopg2 prerequisites
     run: sudo apt-get install libpq-dev
   - name: Install dependencies and config
     run: |
       pip install --upgrade setuptools wheel
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       cp decide/local_settings.gactions.py decide/local_settings.py
 
   - name: docker login
     env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
     run:
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
   - name: Build the Docker image
     run: docker build . --file docker/Dockerfile --tag chamodshehanka/node-test:$(date +%s)
 
   - name: Docker Push
     run: docker push ${{secrets.DOCKER_USER}}/decide-part-rota