name: Docker deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag chamodshehanka/node-test:$(date +%s)

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/decide-part-rota